title: Stilte retraite
short_title: Stilte retraite
description: Website voor stilte retraite
baseurl:
permalink: "/:path/"
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
collections:
  people:
    output: true
    permalink: "/about/:path/"
  posts:
    output: true
    permalink: "/posts/:path/"
  events:
    output: true
    permalink: "/events/:path/"
  locations:
    output: true
    permalink: "/locations/:path/"
  videos:
    output: true
    permalink: "/videos/:path/"
  projects:
    output: true
    permalink: "/projects/:path/"
# tag_page_layout: tag_page
# tag_page_dir: tag
jekyll-archives:
  enabled: all
  layout: "archive"
plugins:
  - jekyll-menus
  - jekyll-feed
  - jekyll-archives
  - jekyll-youtube
pagination:
  enabled: true
  per_page: 20
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2
