---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Content
- type: jekyll-posts
  label: Posts
  create: all
  templates:
  - post
- type: jekyll-pages
  label: Pages
  create: all
  templates:
  - landing-page
  - overview
  - page
  - videos
  - events
  - testimonials
  - team
  - locations
  - contact
  - sign-up
- type: directory
  path: _people
  label: People
  create: all
  match: "*"
  templates:
  - person
- type: directory
  path: _events
  label: Events
  create: documents
  match: "*"
  templates:
  - event
- type: directory
  path: _locations
  label: Location
  create: documents
  match: "*"
  templates:
  - location
- type: directory
  path: _videos
  label: Videos
  create: all
  match: "*"
  templates:
  - video
- type: document
  path: _data/information.yml
  label: Contact Information
- type: document
  path: _data/footer.yml
  label: Footer
upload_dir: uploads
public_path: https://static.stilteretraite.nl/uploads
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
