backend:
  name: git-gateway
  branch: master
media_folder: "uploads"
public_folder: "uploads"
collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "/posts/{{slug}}/"
    fields:
      - {label: "Title", name: "title", widget: "string"}