backend:
  name: git-gateway
  branch: netlify
media_folder: "uploads"
public_folder: "uploads"
collections:
  - name: "persons"
    label: "Persons"
    folder: "_people"
    create: true
    fields:
      - label: Meta
        name: meta
        widget: object
        collapsed: true
        fields:
          - {label: "Title", name: "title", widget: "string", required: false}
          - {label: "Keywords", name: "keywords", widget: "string", required: false}
          - {label: "Description", name: "description", widget: "string", required: false}
          - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sub heading", name: "sub_heading", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Thumbnail (Square image, Max 500 pixels)", name: "thumbnail", widget: "image"}
      - {label: "Email", name: "email", widget: "string", required: false}
      - {label: "Link to details", name: "link_to_details", widget: "boolean", required: false}
      - {label: "Hidden", name: "hidden", widget: "boolean", required: false}
      - {label: "Layout", name: "layout", widget: "hidden", default: "member"}
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - label: Meta
        name: meta
        widget: object
        collapsed: true
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Keywords", name: "keywords", widget: "string"}
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Author", name: "author", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Banner image (Ideal dimensions 2500px by 1200px)", name: "banner_image", widget: "image"}
      - {label: "Lead text", name: "lead_text", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - label: Author
        name: author
        widget: relation
        collection: persons
        search_fields: [title]
        value_field: "_people/{{slug}}.md"
        display_fields: ["title"]
      - {label: "Categories", name: "categories", widget: "list", required: false}
      - label: Related posts
        name: related_posts
        widget: relation
        collection: posts
        search_fields: [title, date]
        value_field: title
        multiple: true
        required: false
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
  - name: "locations"
    label: "Locations"
    folder: "_locations"
    create: true
    fields:
      - label: Meta
        name: meta
        widget: object
        collapsed: true
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Keywords", name: "keywords", widget: "string"}
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Author", name: "author", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Gallery", name: "gallery", widget: "image", media_library: {config: {multiple: true}}}
      - {label: "Layout", name: "layout", widget: "hidden", default: "location"}
      - {label: "Style", name: "style", widget: "hidden", default: "<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css\" />"}
      - {label: "Script", name: "script", widget: "hidden", default: "<script src=\"https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js\"></script>"}
  - name: "events"
    label: "Events"
    folder: "_events"
    create: true
    fields:
      - label: Meta
        name: meta
        widget: object
        collapsed: true
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Keywords", name: "keywords", widget: "string"}
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Author", name: "author", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Lead text", name: "lead_text", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: Location
        name: location
        widget: relation
        collection: locations
        search_fields: [title]
        value_field: "_locations/{{slug}}.md"
        display_fields: ["title"]
      - {label: "From date", name: "from_date", widget: "date"}
      - {label: "To date", name: "to_date", widget: "date"}
      - {label: "Length of time", name: "length_of_time", widget: "string"}
      - {label: "Price", name: "price", widget: "number", value_type: "int", default: 1, min: 1, step: 1}
      - {label: "Attendees", name: "attendees", widget: "number", value_type: "int", default: 1, min: 1, step: 1}
      - {label: "Category", name: "category", widget: "select", options: [{label: "1 day", value: "1-day"}, {label: "Weekend", value: "weekend"}, {label: "4 days", value: "4-days"}, {label: "5 days", value: "5-days"}, {label: "7 day", value: "7-days"}, {label: "10 days", value: "10-days"}]}
      - {label: "Layout", name: "layout", widget: "hidden", default: "event"}
  - name: "testimonials"
    label: "Testimonials"
    files:
      - name: "testimonials"
        label: "Testimonials"
        file: "ervaringen.md"
        fields:
        - label: Meta
          name: meta
          widget: object
          collapsed: true
          fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Keywords", name: "keywords", widget: "string"}
            - {label: "Description", name: "description", widget: "string"}
            - {label: "Author", name: "author", widget: "string"}
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Image", name: "image", widget: "image"}
        - {label: "Layout", name: "layout", widget: "hidden", default: "testimonials"}
        - label: Testimonials
          name: testimonials
          widget: list
          fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Text", name: "text", widget: "markdown"}
          - {label: "Participant", name: "participant", widget: "string"}
